version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cipherdrop
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:toor@postgres/db
    ports:
      - "8080:8080"
    command: >
      sh -c "
      until diesel migration run; do
        echo 'Waiting for database migration...'
      done &&
      ./backend
      "

volumes:
  postgres_data:
    driver: local