name: Deploy to cipherdrop.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run deployment
      run: |
        ssh -o StrictHostKeyChecking=no root@cipherdrop.sh << 'EOF'
          set -e
          trap 'docker compose up -d' ERR

          cd /root/CipherDrop
          git reset --hard
          git pull

          cd backend
          diesel migration run

          cd ..
          docker compose build backend

          docker compose down
          sleep 5
          docker network rm cipherdrop_default || true

          docker compose up -d

          docker image prune -f
          docker container prune -f
        EOF
